package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "carrera", catalog = "seguimientoalegresado")
public class Carrera implements java.io.Serializable {

	private Integer idCarrera;
	private String nombreCarrera;
	private Set<Perfilacademico> perfilacademicos = new HashSet<Perfilacademico>(0);

	public Carrera() {
	}

	public Carrera(String nombreCarrera, Set<Perfilacademico> perfilacademicos) {
		this.nombreCarrera = nombreCarrera;
		this.perfilacademicos = perfilacademicos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCarrera", unique = true, nullable = false)
	public Integer getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(Integer idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "nombreCarrera", length = 40)
	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<Perfilacademico> getPerfilacademicos() {
		return this.perfilacademicos;
	}

	public void setPerfilacademicos(Set<Perfilacademico> perfilacademicos) {
		this.perfilacademicos = perfilacademicos;
	}

}
