package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", catalog = "seguimientoalegresado")
public class Departamento implements java.io.Serializable {

	private Integer idDepartamento;
	private String nombreDepartamento;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);

	public Departamento() {
	}

	public Departamento(String nombreDepartamento, Set<Direccion> direccions) {
		this.nombreDepartamento = nombreDepartamento;
		this.direccions = direccions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDepartamento", unique = true, nullable = false)
	public Integer getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(Integer idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	@Column(name = "nombreDepartamento", length = 40)
	public String getNombreDepartamento() {
		return this.nombreDepartamento;
	}

	public void setNombreDepartamento(String nombreDepartamento) {
		this.nombreDepartamento = nombreDepartamento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
