package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", catalog = "seguimientoalegresado")
public class Direccion implements java.io.Serializable {

	private Integer idDireccion;
	private Departamento departamento;
	private String nombreDireccion;
	private String referenciaDireccion;
	private String nombreProvincia;
	private String nombreDistrito;
	private Set<Egresado> egresados = new HashSet<Egresado>(0);

	public Direccion() {
	}

	public Direccion(Departamento departamento, String nombreDireccion, String referenciaDireccion,
			String nombreProvincia, String nombreDistrito, Set<Egresado> egresados) {
		this.departamento = departamento;
		this.nombreDireccion = nombreDireccion;
		this.referenciaDireccion = referenciaDireccion;
		this.nombreProvincia = nombreProvincia;
		this.nombreDistrito = nombreDistrito;
		this.egresados = egresados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDireccion", unique = true, nullable = false)
	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDepartamento")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "nombreDireccion", length = 120)
	public String getNombreDireccion() {
		return this.nombreDireccion;
	}

	public void setNombreDireccion(String nombreDireccion) {
		this.nombreDireccion = nombreDireccion;
	}

	@Column(name = "referenciaDireccion", length = 120)
	public String getReferenciaDireccion() {
		return this.referenciaDireccion;
	}

	public void setReferenciaDireccion(String referenciaDireccion) {
		this.referenciaDireccion = referenciaDireccion;
	}

	@Column(name = "nombreProvincia", length = 40)
	public String getNombreProvincia() {
		return this.nombreProvincia;
	}

	public void setNombreProvincia(String nombreProvincia) {
		this.nombreProvincia = nombreProvincia;
	}

	@Column(name = "nombreDistrito", length = 40)
	public String getNombreDistrito() {
		return this.nombreDistrito;
	}

	public void setNombreDistrito(String nombreDistrito) {
		this.nombreDistrito = nombreDistrito;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccion")
	public Set<Egresado> getEgresados() {
		return this.egresados;
	}

	public void setEgresados(Set<Egresado> egresados) {
		this.egresados = egresados;
	}

}
