package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadocivil generated by hbm2java
 */
@Entity
@Table(name = "estadocivil", catalog = "seguimientoalegresado")
public class Estadocivil implements java.io.Serializable {

	private Integer idEstadoCivil;
	private String nombreEstadoCivil;
	private Set<Egresado> egresados = new HashSet<Egresado>(0);

	public Estadocivil() {
	}

	public Estadocivil(String nombreEstadoCivil, Set<Egresado> egresados) {
		this.nombreEstadoCivil = nombreEstadoCivil;
		this.egresados = egresados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEstadoCivil", unique = true, nullable = false)
	public Integer getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(Integer idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	@Column(name = "nombreEstadoCivil", length = 40)
	public String getNombreEstadoCivil() {
		return this.nombreEstadoCivil;
	}

	public void setNombreEstadoCivil(String nombreEstadoCivil) {
		this.nombreEstadoCivil = nombreEstadoCivil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadocivil")
	public Set<Egresado> getEgresados() {
		return this.egresados;
	}

	public void setEgresados(Set<Egresado> egresados) {
		this.egresados = egresados;
	}

}
