package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modalidadestudio generated by hbm2java
 */
@Entity
@Table(name = "modalidadestudio", catalog = "seguimientoalegresado")
public class Modalidadestudio implements java.io.Serializable {

	private Integer idModalidadEstudio;
	private String nombreModalidadEstudio;
	private String rangoFecha;
	private Set<Perfilacademico> perfilacademicos = new HashSet<Perfilacademico>(0);

	public Modalidadestudio() {
	}

	public Modalidadestudio(String nombreModalidadEstudio, String rangoFecha, Set<Perfilacademico> perfilacademicos) {
		this.nombreModalidadEstudio = nombreModalidadEstudio;
		this.rangoFecha = rangoFecha;
		this.perfilacademicos = perfilacademicos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModalidadEstudio", unique = true, nullable = false)
	public Integer getIdModalidadEstudio() {
		return this.idModalidadEstudio;
	}

	public void setIdModalidadEstudio(Integer idModalidadEstudio) {
		this.idModalidadEstudio = idModalidadEstudio;
	}

	@Column(name = "nombreModalidadEstudio", length = 50)
	public String getNombreModalidadEstudio() {
		return this.nombreModalidadEstudio;
	}

	public void setNombreModalidadEstudio(String nombreModalidadEstudio) {
		this.nombreModalidadEstudio = nombreModalidadEstudio;
	}

	@Column(name = "rangoFecha", length = 30)
	public String getRangoFecha() {
		return this.rangoFecha;
	}

	public void setRangoFecha(String rangoFecha) {
		this.rangoFecha = rangoFecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modalidadestudio")
	public Set<Perfilacademico> getPerfilacademicos() {
		return this.perfilacademicos;
	}

	public void setPerfilacademicos(Set<Perfilacademico> perfilacademicos) {
		this.perfilacademicos = perfilacademicos;
	}

}
