package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", catalog = "seguimientoalegresado")
public class Modulo implements java.io.Serializable {

	private Integer idModulo;
	private String nombre;
	private String icono;
	private Set<Submodulo> submodulos = new HashSet<Submodulo>(0);

	public Modulo() {
	}

	public Modulo(String nombre, String icono, Set<Submodulo> submodulos) {
		this.nombre = nombre;
		this.icono = icono;
		this.submodulos = submodulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModulo", unique = true, nullable = false)
	public Integer getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(Integer idModulo) {
		this.idModulo = idModulo;
	}

	@Column(name = "nombre", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "icono", length = 40)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modulo")
	public Set<Submodulo> getSubmodulos() {
		return this.submodulos;
	}

	public void setSubmodulos(Set<Submodulo> submodulos) {
		this.submodulos = submodulos;
	}

}
