package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Motivosituacionegresado generated by hbm2java
 */
@Entity
@Table(name = "motivosituacionegresado", catalog = "seguimientoalegresado")
public class Motivosituacionegresado implements java.io.Serializable {

	private Integer idMotivoSituacionEgresado;
	private String nombreMotivoSituacionEgresado;
	private Set<Perfilacademico> perfilacademicos = new HashSet<Perfilacademico>(0);

	public Motivosituacionegresado() {
	}

	public Motivosituacionegresado(String nombreMotivoSituacionEgresado, Set<Perfilacademico> perfilacademicos) {
		this.nombreMotivoSituacionEgresado = nombreMotivoSituacionEgresado;
		this.perfilacademicos = perfilacademicos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMotivoSituacionEgresado", unique = true, nullable = false)
	public Integer getIdMotivoSituacionEgresado() {
		return this.idMotivoSituacionEgresado;
	}

	public void setIdMotivoSituacionEgresado(Integer idMotivoSituacionEgresado) {
		this.idMotivoSituacionEgresado = idMotivoSituacionEgresado;
	}

	@Column(name = "nombreMotivoSituacionEgresado", length = 50)
	public String getNombreMotivoSituacionEgresado() {
		return this.nombreMotivoSituacionEgresado;
	}

	public void setNombreMotivoSituacionEgresado(String nombreMotivoSituacionEgresado) {
		this.nombreMotivoSituacionEgresado = nombreMotivoSituacionEgresado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motivosituacionegresado")
	public Set<Perfilacademico> getPerfilacademicos() {
		return this.perfilacademicos;
	}

	public void setPerfilacademicos(Set<Perfilacademico> perfilacademicos) {
		this.perfilacademicos = perfilacademicos;
	}

}
