package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Noticia generated by hbm2java
 */
@Entity
@Table(name = "noticia", catalog = "seguimientoalegresado")
public class Noticia implements java.io.Serializable {

	private Integer idNoticia;
	private Usuario usuario;
	private String descripcionNoticia;
	private String urlFoto;
	private Date fechaPublicacion;
	private Date fechaDespublicacion;
	private Byte estado;

	public Noticia() {
	}

	public Noticia(Usuario usuario, String descripcionNoticia, String urlFoto, Date fechaPublicacion,
			Date fechaDespublicacion, Byte estado) {
		this.usuario = usuario;
		this.descripcionNoticia = descripcionNoticia;
		this.urlFoto = urlFoto;
		this.fechaPublicacion = fechaPublicacion;
		this.fechaDespublicacion = fechaDespublicacion;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idNoticia", unique = true, nullable = false)
	public Integer getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(Integer idNoticia) {
		this.idNoticia = idNoticia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "descripcionNoticia")
	public String getDescripcionNoticia() {
		return this.descripcionNoticia;
	}

	public void setDescripcionNoticia(String descripcionNoticia) {
		this.descripcionNoticia = descripcionNoticia;
	}

	@Column(name = "urlFoto", length = 500)
	public String getUrlFoto() {
		return this.urlFoto;
	}

	public void setUrlFoto(String urlFoto) {
		this.urlFoto = urlFoto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaPublicacion", length = 10)
	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaDespublicacion", length = 10)
	public Date getFechaDespublicacion() {
		return this.fechaDespublicacion;
	}

	public void setFechaDespublicacion(Date fechaDespublicacion) {
		this.fechaDespublicacion = fechaDespublicacion;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

}
