package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name = "opcion", catalog = "seguimientoalegresado")
public class Opcion implements java.io.Serializable {

	private Integer idOpcion;
	private Submodulo submodulo;
	private String nombre;
	private String icon;
	private Set<Permiso> permisos = new HashSet<Permiso>(0);

	public Opcion() {
	}

	public Opcion(Submodulo submodulo, String nombre, String icon, Set<Permiso> permisos) {
		this.submodulo = submodulo;
		this.nombre = nombre;
		this.icon = icon;
		this.permisos = permisos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idOpcion", unique = true, nullable = false)
	public Integer getIdOpcion() {
		return this.idOpcion;
	}

	public void setIdOpcion(Integer idOpcion) {
		this.idOpcion = idOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSubModulo")
	public Submodulo getSubmodulo() {
		return this.submodulo;
	}

	public void setSubmodulo(Submodulo submodulo) {
		this.submodulo = submodulo;
	}

	@Column(name = "nombre", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "icon", length = 30)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<Permiso> getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

}
