package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfilacademico generated by hbm2java
 */
@Entity
@Table(name = "perfilacademico", catalog = "seguimientoalegresado")
public class Perfilacademico implements java.io.Serializable {

	private Integer idPerfilAcademico;
	private Carrera carrera;
	private Modalidadestudio modalidadestudio;
	private Motivosituacionegresado motivosituacionegresado;
	private Situacionegresado situacionegresado;
	private Integer anoIngreso;
	private Integer anoEgreso;
	private Integer anoTitulacion;
	private String detalleMotivoSituacionEgresado;
	private Set<Egresado> egresados = new HashSet<Egresado>(0);

	public Perfilacademico() {
	}

	public Perfilacademico(Carrera carrera, Modalidadestudio modalidadestudio,
			Motivosituacionegresado motivosituacionegresado, Situacionegresado situacionegresado, Integer anoIngreso,
			Integer anoEgreso, Integer anoTitulacion, String detalleMotivoSituacionEgresado, Set<Egresado> egresados) {
		this.carrera = carrera;
		this.modalidadestudio = modalidadestudio;
		this.motivosituacionegresado = motivosituacionegresado;
		this.situacionegresado = situacionegresado;
		this.anoIngreso = anoIngreso;
		this.anoEgreso = anoEgreso;
		this.anoTitulacion = anoTitulacion;
		this.detalleMotivoSituacionEgresado = detalleMotivoSituacionEgresado;
		this.egresados = egresados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPerfilAcademico", unique = true, nullable = false)
	public Integer getIdPerfilAcademico() {
		return this.idPerfilAcademico;
	}

	public void setIdPerfilAcademico(Integer idPerfilAcademico) {
		this.idPerfilAcademico = idPerfilAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCarrera")
	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idModalidadEstudio")
	public Modalidadestudio getModalidadestudio() {
		return this.modalidadestudio;
	}

	public void setModalidadestudio(Modalidadestudio modalidadestudio) {
		this.modalidadestudio = modalidadestudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMotivoSituacionEgresado")
	public Motivosituacionegresado getMotivosituacionegresado() {
		return this.motivosituacionegresado;
	}

	public void setMotivosituacionegresado(Motivosituacionegresado motivosituacionegresado) {
		this.motivosituacionegresado = motivosituacionegresado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSituacionEgresado")
	public Situacionegresado getSituacionegresado() {
		return this.situacionegresado;
	}

	public void setSituacionegresado(Situacionegresado situacionegresado) {
		this.situacionegresado = situacionegresado;
	}

	@Column(name = "anoIngreso")
	public Integer getAnoIngreso() {
		return this.anoIngreso;
	}

	public void setAnoIngreso(Integer anoIngreso) {
		this.anoIngreso = anoIngreso;
	}

	@Column(name = "anoEgreso")
	public Integer getAnoEgreso() {
		return this.anoEgreso;
	}

	public void setAnoEgreso(Integer anoEgreso) {
		this.anoEgreso = anoEgreso;
	}

	@Column(name = "anoTitulacion")
	public Integer getAnoTitulacion() {
		return this.anoTitulacion;
	}

	public void setAnoTitulacion(Integer anoTitulacion) {
		this.anoTitulacion = anoTitulacion;
	}

	@Column(name = "detalleMotivoSituacionEgresado", length = 50)
	public String getDetalleMotivoSituacionEgresado() {
		return this.detalleMotivoSituacionEgresado;
	}

	public void setDetalleMotivoSituacionEgresado(String detalleMotivoSituacionEgresado) {
		this.detalleMotivoSituacionEgresado = detalleMotivoSituacionEgresado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfilacademico")
	public Set<Egresado> getEgresados() {
		return this.egresados;
	}

	public void setEgresados(Set<Egresado> egresados) {
		this.egresados = egresados;
	}

}
