package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Primerempleo generated by hbm2java
 */
@Entity
@Table(name = "primerempleo", catalog = "seguimientoalegresado")
public class Primerempleo implements java.io.Serializable {

	private Integer idPrimerEmpleo;
	private Egresado egresado;
	private Sectorinstitucion sectorinstitucion;
	private Tipoaccesoalempleo tipoaccesoalempleo;
	private Byte trabajoDuranteEstudios;
	private Byte relacionadoConFormacion;
	private String nombreInstitucion;
	private String cargoEmpleo;
	private Date fechaInicio;
	private Date fechaTermino;
	private String tipoContrato;
	private String nombreDireccion;
	private Byte estado;
	private Integer mesesAntesDelPrimerEmpleo;
	private String detalleAccesoAlEmpleo;

	public Primerempleo() {
	}

	public Primerempleo(Egresado egresado, Sectorinstitucion sectorinstitucion, Tipoaccesoalempleo tipoaccesoalempleo,
			Byte trabajoDuranteEstudios, Byte relacionadoConFormacion, String nombreInstitucion, String cargoEmpleo,
			Date fechaInicio, Date fechaTermino, String tipoContrato, String nombreDireccion, Byte estado,
			Integer mesesAntesDelPrimerEmpleo, String detalleAccesoAlEmpleo) {
		this.egresado = egresado;
		this.sectorinstitucion = sectorinstitucion;
		this.tipoaccesoalempleo = tipoaccesoalempleo;
		this.trabajoDuranteEstudios = trabajoDuranteEstudios;
		this.relacionadoConFormacion = relacionadoConFormacion;
		this.nombreInstitucion = nombreInstitucion;
		this.cargoEmpleo = cargoEmpleo;
		this.fechaInicio = fechaInicio;
		this.fechaTermino = fechaTermino;
		this.tipoContrato = tipoContrato;
		this.nombreDireccion = nombreDireccion;
		this.estado = estado;
		this.mesesAntesDelPrimerEmpleo = mesesAntesDelPrimerEmpleo;
		this.detalleAccesoAlEmpleo = detalleAccesoAlEmpleo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPrimerEmpleo", unique = true, nullable = false)
	public Integer getIdPrimerEmpleo() {
		return this.idPrimerEmpleo;
	}

	public void setIdPrimerEmpleo(Integer idPrimerEmpleo) {
		this.idPrimerEmpleo = idPrimerEmpleo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEgresado")
	public Egresado getEgresado() {
		return this.egresado;
	}

	public void setEgresado(Egresado egresado) {
		this.egresado = egresado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSectorInstitucion")
	public Sectorinstitucion getSectorinstitucion() {
		return this.sectorinstitucion;
	}

	public void setSectorinstitucion(Sectorinstitucion sectorinstitucion) {
		this.sectorinstitucion = sectorinstitucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoAccesoAlEmpleo")
	public Tipoaccesoalempleo getTipoaccesoalempleo() {
		return this.tipoaccesoalempleo;
	}

	public void setTipoaccesoalempleo(Tipoaccesoalempleo tipoaccesoalempleo) {
		this.tipoaccesoalempleo = tipoaccesoalempleo;
	}

	@Column(name = "trabajoDuranteEstudios")
	public Byte getTrabajoDuranteEstudios() {
		return this.trabajoDuranteEstudios;
	}

	public void setTrabajoDuranteEstudios(Byte trabajoDuranteEstudios) {
		this.trabajoDuranteEstudios = trabajoDuranteEstudios;
	}

	@Column(name = "relacionadoConFormacion")
	public Byte getRelacionadoConFormacion() {
		return this.relacionadoConFormacion;
	}

	public void setRelacionadoConFormacion(Byte relacionadoConFormacion) {
		this.relacionadoConFormacion = relacionadoConFormacion;
	}

	@Column(name = "nombreInstitucion", length = 50)
	public String getNombreInstitucion() {
		return this.nombreInstitucion;
	}

	public void setNombreInstitucion(String nombreInstitucion) {
		this.nombreInstitucion = nombreInstitucion;
	}

	@Column(name = "cargoEmpleo", length = 50)
	public String getCargoEmpleo() {
		return this.cargoEmpleo;
	}

	public void setCargoEmpleo(String cargoEmpleo) {
		this.cargoEmpleo = cargoEmpleo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicio", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaTermino", length = 10)
	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	@Column(name = "tipoContrato", length = 50)
	public String getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(String tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Column(name = "nombreDireccion", length = 120)
	public String getNombreDireccion() {
		return this.nombreDireccion;
	}

	public void setNombreDireccion(String nombreDireccion) {
		this.nombreDireccion = nombreDireccion;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	@Column(name = "mesesAntesDelPrimerEmpleo")
	public Integer getMesesAntesDelPrimerEmpleo() {
		return this.mesesAntesDelPrimerEmpleo;
	}

	public void setMesesAntesDelPrimerEmpleo(Integer mesesAntesDelPrimerEmpleo) {
		this.mesesAntesDelPrimerEmpleo = mesesAntesDelPrimerEmpleo;
	}

	@Column(name = "detalleAccesoAlEmpleo", length = 200)
	public String getDetalleAccesoAlEmpleo() {
		return this.detalleAccesoAlEmpleo;
	}

	public void setDetalleAccesoAlEmpleo(String detalleAccesoAlEmpleo) {
		this.detalleAccesoAlEmpleo = detalleAccesoAlEmpleo;
	}

}
