package pe.edu.udaff.entities;
// Generated 07-nov-2019 2:39:02 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Propuesta generated by hbm2java
 */
@Entity
@Table(name = "propuesta", catalog = "seguimientoalegresado")
public class Propuesta implements java.io.Serializable {

	private Integer idPropuesta;
	private Tipopropuesta tipopropuesta;
	private Usuario usuario;
	private String descripcionPropuesta;
	private Date fecha;

	public Propuesta() {
	}

	public Propuesta(Tipopropuesta tipopropuesta, Usuario usuario, String descripcionPropuesta, Date fecha) {
		this.tipopropuesta = tipopropuesta;
		this.usuario = usuario;
		this.descripcionPropuesta = descripcionPropuesta;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPropuesta", unique = true, nullable = false)
	public Integer getIdPropuesta() {
		return this.idPropuesta;
	}

	public void setIdPropuesta(Integer idPropuesta) {
		this.idPropuesta = idPropuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoPropuesta")
	public Tipopropuesta getTipopropuesta() {
		return this.tipopropuesta;
	}

	public void setTipopropuesta(Tipopropuesta tipopropuesta) {
		this.tipopropuesta = tipopropuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "descripcionPropuesta", length = 200)
	public String getDescripcionPropuesta() {
		return this.descripcionPropuesta;
	}

	public void setDescripcionPropuesta(String descripcionPropuesta) {
		this.descripcionPropuesta = descripcionPropuesta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
