package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Propuesta generated by hbm2java
 */
@Entity
@Table(name = "propuesta", catalog = "seguimientoalegresado")
public class Propuesta implements java.io.Serializable {

	private Integer idPropuesta;
	private Tipopropuesta tipopropuesta;
	private String descripcionPropuesta;

	public Propuesta() {
	}

	public Propuesta(Tipopropuesta tipopropuesta, String descripcionPropuesta) {
		this.tipopropuesta = tipopropuesta;
		this.descripcionPropuesta = descripcionPropuesta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPropuesta", unique = true, nullable = false)
	public Integer getIdPropuesta() {
		return this.idPropuesta;
	}

	public void setIdPropuesta(Integer idPropuesta) {
		this.idPropuesta = idPropuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoPropuesta")
	public Tipopropuesta getTipopropuesta() {
		return this.tipopropuesta;
	}

	public void setTipopropuesta(Tipopropuesta tipopropuesta) {
		this.tipopropuesta = tipopropuesta;
	}

	@Column(name = "descripcionPropuesta", length = 200)
	public String getDescripcionPropuesta() {
		return this.descripcionPropuesta;
	}

	public void setDescripcionPropuesta(String descripcionPropuesta) {
		this.descripcionPropuesta = descripcionPropuesta;
	}

}
