package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sectorinstitucion generated by hbm2java
 */
@Entity
@Table(name = "sectorinstitucion", catalog = "seguimientoalegresado")
public class Sectorinstitucion implements java.io.Serializable {

	private Integer idSectorInstitucion;
	private String nombreSectorInstitucion;
	private Set<Primerempleo> primerempleos = new HashSet<Primerempleo>(0);
	private Set<Antecedentelaboral> antecedentelaborals = new HashSet<Antecedentelaboral>(0);

	public Sectorinstitucion() {
	}

	public Sectorinstitucion(String nombreSectorInstitucion, Set<Primerempleo> primerempleos,
			Set<Antecedentelaboral> antecedentelaborals) {
		this.nombreSectorInstitucion = nombreSectorInstitucion;
		this.primerempleos = primerempleos;
		this.antecedentelaborals = antecedentelaborals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSectorInstitucion", unique = true, nullable = false)
	public Integer getIdSectorInstitucion() {
		return this.idSectorInstitucion;
	}

	public void setIdSectorInstitucion(Integer idSectorInstitucion) {
		this.idSectorInstitucion = idSectorInstitucion;
	}

	@Column(name = "nombreSectorInstitucion", length = 40)
	public String getNombreSectorInstitucion() {
		return this.nombreSectorInstitucion;
	}

	public void setNombreSectorInstitucion(String nombreSectorInstitucion) {
		this.nombreSectorInstitucion = nombreSectorInstitucion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectorinstitucion")
	public Set<Primerempleo> getPrimerempleos() {
		return this.primerempleos;
	}

	public void setPrimerempleos(Set<Primerempleo> primerempleos) {
		this.primerempleos = primerempleos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectorinstitucion")
	public Set<Antecedentelaboral> getAntecedentelaborals() {
		return this.antecedentelaborals;
	}

	public void setAntecedentelaborals(Set<Antecedentelaboral> antecedentelaborals) {
		this.antecedentelaborals = antecedentelaborals;
	}

}
