package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name = "sexo", catalog = "seguimientoalegresado")
public class Sexo implements java.io.Serializable {

	private Integer idSexo;
	private String nombreSexo;
	private Set<Egresado> egresados = new HashSet<Egresado>(0);

	public Sexo() {
	}

	public Sexo(String nombreSexo, Set<Egresado> egresados) {
		this.nombreSexo = nombreSexo;
		this.egresados = egresados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSexo", unique = true, nullable = false)
	public Integer getIdSexo() {
		return this.idSexo;
	}

	public void setIdSexo(Integer idSexo) {
		this.idSexo = idSexo;
	}

	@Column(name = "nombreSexo", length = 40)
	public String getNombreSexo() {
		return this.nombreSexo;
	}

	public void setNombreSexo(String nombreSexo) {
		this.nombreSexo = nombreSexo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sexo")
	public Set<Egresado> getEgresados() {
		return this.egresados;
	}

	public void setEgresados(Set<Egresado> egresados) {
		this.egresados = egresados;
	}

}
