package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Situacionegresado generated by hbm2java
 */
@Entity
@Table(name = "situacionegresado", catalog = "seguimientoalegresado")
public class Situacionegresado implements java.io.Serializable {

	private Integer idSituacionEgresado;
	private String nombreSituacionEgresado;
	private Set<Perfilacademico> perfilacademicos = new HashSet<Perfilacademico>(0);

	public Situacionegresado() {
	}

	public Situacionegresado(String nombreSituacionEgresado, Set<Perfilacademico> perfilacademicos) {
		this.nombreSituacionEgresado = nombreSituacionEgresado;
		this.perfilacademicos = perfilacademicos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSituacionEgresado", unique = true, nullable = false)
	public Integer getIdSituacionEgresado() {
		return this.idSituacionEgresado;
	}

	public void setIdSituacionEgresado(Integer idSituacionEgresado) {
		this.idSituacionEgresado = idSituacionEgresado;
	}

	@Column(name = "nombreSituacionEgresado", length = 50)
	public String getNombreSituacionEgresado() {
		return this.nombreSituacionEgresado;
	}

	public void setNombreSituacionEgresado(String nombreSituacionEgresado) {
		this.nombreSituacionEgresado = nombreSituacionEgresado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situacionegresado")
	public Set<Perfilacademico> getPerfilacademicos() {
		return this.perfilacademicos;
	}

	public void setPerfilacademicos(Set<Perfilacademico> perfilacademicos) {
		this.perfilacademicos = perfilacademicos;
	}

}
