package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Submodulo generated by hbm2java
 */
@Entity
@Table(name = "submodulo", catalog = "seguimientoalegresado")
public class Submodulo implements java.io.Serializable {

	private Integer idSubModulo;
	private Modulo modulo;
	private String nombre;
	private String url;
	private Set<Opcion> opcions = new HashSet<Opcion>(0);

	public Submodulo() {
	}

	public Submodulo(Modulo modulo, String nombre, String url, Set<Opcion> opcions) {
		this.modulo = modulo;
		this.nombre = nombre;
		this.url = url;
		this.opcions = opcions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSubModulo", unique = true, nullable = false)
	public Integer getIdSubModulo() {
		return this.idSubModulo;
	}

	public void setIdSubModulo(Integer idSubModulo) {
		this.idSubModulo = idSubModulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idModulo")
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@Column(name = "nombre", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "submodulo")
	public Set<Opcion> getOpcions() {
		return this.opcions;
	}

	public void setOpcions(Set<Opcion> opcions) {
		this.opcions = opcions;
	}

}
