package pe.edu.udaff.entities;
// Generated 06-nov-2019 10:11:51 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoaccesoalempleo generated by hbm2java
 */
@Entity
@Table(name = "tipoaccesoalempleo", catalog = "seguimientoalegresado")
public class Tipoaccesoalempleo implements java.io.Serializable {

	private Integer idTipoAccesoAlEmpleo;
	private String nombreTipoAccesoAlEmpleo;
	private Set<Primerempleo> primerempleos = new HashSet<Primerempleo>(0);

	public Tipoaccesoalempleo() {
	}

	public Tipoaccesoalempleo(String nombreTipoAccesoAlEmpleo, Set<Primerempleo> primerempleos) {
		this.nombreTipoAccesoAlEmpleo = nombreTipoAccesoAlEmpleo;
		this.primerempleos = primerempleos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoAccesoAlEmpleo", unique = true, nullable = false)
	public Integer getIdTipoAccesoAlEmpleo() {
		return this.idTipoAccesoAlEmpleo;
	}

	public void setIdTipoAccesoAlEmpleo(Integer idTipoAccesoAlEmpleo) {
		this.idTipoAccesoAlEmpleo = idTipoAccesoAlEmpleo;
	}

	@Column(name = "nombreTipoAccesoAlEmpleo", length = 50)
	public String getNombreTipoAccesoAlEmpleo() {
		return this.nombreTipoAccesoAlEmpleo;
	}

	public void setNombreTipoAccesoAlEmpleo(String nombreTipoAccesoAlEmpleo) {
		this.nombreTipoAccesoAlEmpleo = nombreTipoAccesoAlEmpleo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoaccesoalempleo")
	public Set<Primerempleo> getPrimerempleos() {
		return this.primerempleos;
	}

	public void setPrimerempleos(Set<Primerempleo> primerempleos) {
		this.primerempleos = primerempleos;
	}

}
